"""Add portfolio fields to Student

Revision ID: 7fa1da8a4085
Revises: 4f6cc5493912
Create Date: 2026-03-04 14:22:27.396528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa1da8a4085'
down_revision = '4f6cc5493912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headline', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('experience')
        batch_op.drop_column('bio')
        batch_op.drop_column('headline')

    # ### end Alembic commands ###
