"""Add user_prefs column

Revision ID: da6308dd7167
Revises: 7fa1da8a4085
Create Date: 2026-04-22 22:16:36.111386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6308dd7167'
down_revision = '7fa1da8a4085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_locked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rating_overridden', sa.Boolean(), nullable=True))

    with op.batch_alter_table('project_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('link', sa.String(length=500), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_prefs', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_prefs')

    with op.batch_alter_table('project_media', schema=None) as batch_op:
        batch_op.drop_column('link')
        batch_op.drop_column('description')

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('rating_overridden')
        batch_op.drop_column('rating_locked')

    # ### end Alembic commands ###
